### PR TITLE
fix: redirect to detail page when creating a link that already exists

### LINKED ISSUE #160: XSRF token mismatch error when using the "create" form to update a link
If I use the create form on `/go/` to update a link that already exists:

Image

Rather than an updated link (my preferred outcome), an intermediate form indicating a collision with an offer to overwrite (probably the right outcome) or an error indicating that the link is duplicated (least ideal), what I instead get is a plain text HTTP response "Invalid XSRF token"

This is sort of related to #130 -- I think it's the same issue, and the users haven't recognized that they are creating duplicates -- and https://github.com/tailscale/golink/issues/156, which is about "renaming" a link.

### PR DESCRIPTION
**Pull request by mikeodr**
When attempting to create a link that already exists, redirect to the details page of the existing link to allow for updating.

Fixes #160

### CODE REVIEW

File: golink.go [hunk 1]
```diff
@@ -981,16 +981,20 @@ func serveSave(w http.ResponseWriter, r *http.Request) {
...
-	if link != nil {
-		tokenShortName = link.Short
-	}
-
-	if !isRequestAuthorized(r, cu, tokenShortName) {
-		http.Error(w, "invalid XSRF token", http.StatusBadRequest)
-		return
+	// Validate the XSRF token. The token may have been generated with either
+	// newShortName (from the home page create form) or the link's actual short
+	// name (from the detail page edit form). Accept either one for existing
```
Comment (willnorris) [inline golink.go]: we actually don't don't want to accept the `.new` token if the link already exists.  This was a problem we had where someone thought they were creating a new link, but were accidentally overwriting an existing link.  The fact that it fails with an XSRF error is a problem and we definitely need a better error message there, but we don't want to allow the accidental overwriting.

**Review by willnorris — APPROVED** [review]

**Comment by mikeodr** [comment]
image

**Review by willnorris — APPROVED** [review]

**Comment by willnorris** [comment]
that screenshot is a little weird because it says you can edit it below, but it's the non-editable version of the detail page :)  Maybe first check if they have access to edit?

**Comment by mikeodr** [comment]
I was mixing users 
image


Maybe yeah let me follow on.
